POST http://localhost/api/user/login
Content-Type: application/json

{
  "username":"ewq",
  "password":"123"
}

###

POST http://localhost/api/user/register
Content-Type: application/json

{
  "username":"eeee",
  "password":"123"
}

###

