CREATE DATABASE IF NOT EXISTS NTMBank
  DEFAULT CHARSET utf8mb4
  COLLATE utf8mb4_general_ci;

USE NTMBank;

CREATE TABLE IF NOT EXISTS accounts (
  username CHAR(32) UNIQUE NOT NULL,
  password CHAR(32)        NOT NULL,
  balance int not null DEFAULT 0,
  user_id  INT AUTO_INCREMENT PRIMARY KEY,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS orders (
  user_id     INT,
  price        INT      NOT NULL,
  orders_id    INT AUTO_INCREMENT PRIMARY KEY,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  FOREIGN KEY (user_id) REFERENCES accounts(user_id)
);