CREATE DATABASE IF NOT EXISTS NTMBank
  DEFAULT CHARSET utf8mb4
  COLLATE utf8mb4_general_ci;

USE NTMBank;

CREATE TABLE IF NOT EXISTS accounts (
  user_id      INT                      AUTO_INCREMENT PRIMARY KEY,
  username     CHAR(32) UNIQUE NOT NULL,
  password     CHAR(32)        NOT NULL,
  balance      INT             NOT NULL DEFAULT 0,
  created_time TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS orders (
  order_id     INT                AUTO_INCREMENT PRIMARY KEY,
  user_id      INT,
  price        INT       NOT NULL,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES accounts (user_id)
);